version: '3'

    ####### NETWORK ########

networks:
  inception:
    name: inception
    driver: bridge

      ##### VOLUMES ######

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/clballes/data/wordpress"
  mariadb_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/clballes/data/mariadb"

      ###### SERVICES #######

services:
  mariadb:
    networks:
      - inception
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_vol:/var/lib/mysql
    restart: always
    expose:
      - "3306"
    image: mariadb:42
  nginx:
    container_name: nginx
    image: nginx:42
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file: .env
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    restart: always
  wordpress:
    image: wordpress:42 
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

